pipeline:
- [run-tests, lint]

jobs:
    run-tests:
        series: jammy
        architectures: amd64
        packages:
          - dctrl-tools
          - file
          - procmail
          - pycodestyle
          - pyflakes3
          - python3
          - python3-apt
          - python3-launchpadlib
          - python3-mock
          - python3-nacl
          - python3-simplestreams
          - squashfs-tools
        run: ./run-tests >output
        output:
            paths: [output]

    lint:
        series: focal
        architectures: amd64
        packages: [tox, git]
        snaps:
            - name: go
              classic: true
        run: tox -e lint
