#! /bin/sh

set -e

# ensure we have our test dependencies
dpkg-checkbuilddeps -d 'dctrl-tools, python3, python3 (>= 3.3) | python3-mock, python3-simplestreams, procmail, squashfs-tools, file' /dev/null

if [ -z "$*" ]; then
	set -- discover cdimage.tests
# the eval shenanigans finds the last argument
elif [ $(eval echo \$$(echo $#)) = "run-tests" ]; then
	set -- discover cdimage.tests
fi

PYTHONPATH=lib python3 -m unittest "$@"
