#! /bin/sh

# Settings for building Ubuntu CD images.

# This will eventually become a more declarative configuration file.  In the
# meantime, do not add new variable settings to this file unless you also
# update lib/cdimage/config.py, or unless their names start with "CDIMAGE_"
# and they are exported to the environment.

export LC_ALL=C

PROJECT="${PROJECT:-ubuntu}"
CAPPROJECT="${CAPPROJECT:-Ubuntu}"
IMAGE_FORMAT=${IMAGE_FORMAT:-iso}
export IMAGE_FORMAT
DIST="${DIST:-resolute}"

case $DIST in
	bionic|focal|jammy|noble)
		PROPOSED="${PROPOSED:-0}"
		export PROPOSED
		;;
esac

# If you want to build image for one or more architectures comment out the
# following line
#ARCHES=i386

# Set this to use lp-signing instead of local gpg
#LP_SIGN_CONFIG="$CDIMAGE_ROOT/secret/lp-sign.conf"

GNUPG_DIR="$CDIMAGE_ROOT/secret/dot-gnupg"
SIGNING_KEYID='EFE21092'

#export LOCAL_SEEDS=file:///path/to/local_seeds

# Do not create source iso
export CDIMAGE_NOSOURCE=1

# Hosts that need to be notified when the build is done.  Third-party users
# will want to keep this variable empty.
# The "async" mirrors will be notified asynchronously, i.e. we won't wait for
# them to respond.
# If these are unset, the contents of
# $CDIMAGE_ROOT/production/trigger-mirrors will be used if present.
TRIGGER_MIRRORS=
TRIGGER_MIRRORS_ASYNC=

export TRIGGER_MIRRORS
export TRIGGER_MIRRORS_ASYNC

umask 002
